### ISSUE TITLE
Cancelling PIN window does not log off account

### ISSUE THREAD

**Issue by diamondo25** [mss-rs/mss-rs#6]

**Comment by elwl** [comment]
How, the ip_address field in table user is not set to null?

**Comment by diamondo25** [comment]
Dunno. What I did was:
1. go to login
2. enter password
3. on pin, enter wrong pin + select change
4. quit the pin window
5. try to login again
6. already logged in
7. wut

**Comment by elwl** [comment]
Try using latest commit

**Comment by elwl** [comment]
This is an interesting bug, as this is the only point in the game where you can go back to the password menu without disconnecting first.
